baseURL = ""
themesdir = "../.."
title = "mdhelp"
theme = "mdhelp"
languageCode = "ja-jp"
DefaultContentLanguage = "jp"
enableInlineShortcodes = true
disablePathToLower= true
enableGitInfo = false
defaultContentLanguageInSubdir= true
hasCJKLanguage = true
uglyurls = true # 各ページのURLを/xxx.html形式(=uglyURL)にする

[params]
    contentRootDir = "content"
    author = "Your Name"
    copyRightFromYear = "2020"
    outputCopyRightToYear = true # trueにするとビルド日をベースに FromYear - toYear とコピーライトを出力します
    isCHM = false
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

[languages]
  [languages.jp]
    baseURL = "."
    languageName = "Japanese"
    contentDir = "content/jp"
    weight = 1
    dateFormat = "2006年01月02日"
    helpLanguageCode = "0x411 Japanese" # for hhp
    htmlcharset = "Shift_JIS" # for Help Html
  [languages.en]
    baseURL = "."
    languageName = "English"
    contentDir = "content/en"
    weight = 2
    dateFormat = "Jan. 2, 2006"
    helpLanguageCode = "0x409 English (US)" # for hhp
    htmlcharset = "UTF-8" # for Help Html

# goldmark settings
[markup.goldmark.renderer]
  hardWraps = true # Markdownのテキストの改行をbrタグにする機能
  unsafe = true # Markdown内のhtmlの有効/無効

# カスタムメディアタイプを指定
# index.hhc -> toc.hhcを生成
# index.hhp -> project.hhpを生成
# index.h   -> Map.hを生成
[mediaTypes]
  [mediaTypes."text/hhc"]
    suffixes = ["hhc"]
  [mediaTypes."text/hhp"]
    suffixes = ["hhp"]
  [mediaTypes."text/map"]
    suffixes = ["h"]
[outputFormats]
  [outputFormats.HHC]
    baseName = "toc"
    isPlainText = true
    mediaType = "text/hhc"
  [outputFormats.HHP]
    baseName = "project"
    isPlainText = true
    mediaType = "text/hhp"
  [outputFormats.MAPTEMP]
    baseName = "MapTemplate"
    isPlainText = true
    mediaType = "text/map"