# publish dir "public_(environment)"という名称にします。
publishDir = "public_chm_other_version"

# content以下の無視するセクション/記事。
#ignoreFiles = ["ignore", "content1/child/test"]

# html以外のファイル類はすべて生成を抑制する
disableKinds = ["taxonomy", "taxonomyTerm", "category", "RSS", "404", "robotsTXT", "sitemap"]

[params]
  # ShowIfショートコード/ShowIfフロントマターで表示するコンテンツの一覧
  showIfs = ["edition1", "edition2", "edition3"]
  isCHM = true

[outputs]
  home = [ "HTML", "HHC", "HHP", "MAPTEMP"] # hhc/hhp/maptemplateも生成
